name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 31.97.129.5
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Navigate to app directory
          cd /home/emailapp/email-app
          
          # Pull latest code
          git pull origin main
          
          # Install and build frontend
          npm install --legacy-peer-deps
          npm run build
          
          # Install backend dependencies
          cd backend
          npm install
          
          # Create .env if not exists
          if [ ! -f .env ]; then
            echo "PORT=3001" > .env
            echo "NODE_ENV=production" >> .env
          fi
          
          # Restart services
          pm2 restart all || (
            pm2 delete all
            pm2 start server.js --name backend
            cd ..
            pm2 serve dist 8080 --name frontend --spa
            pm2 save --force
          )
          
          # Restart Nginx
          systemctl restart nginx
          
          # Show status
          echo "=== Deployment Complete ==="
          pm2 status
          echo "=== Checking Services ==="
          netstat -tlnp | grep -E ':80|:3001|:8080' | grep LISTEN