name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 31.97.129.5
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/emailapp/email-app
          git pull
          npm install
          npm run build
          cd backend && npm install
          pm2 restart all
          echo "Deployed successfully!"